### ISSUE TITLE
Generate proper README.md

### ISSUE THREAD

**Issue by Jam-Burger** [Jam-Burger/woc5.0-android-social_media_app-Jay#5]
Remake the README.md which contains
- All features list
- Cool screenshots

**Comment by indra057** [comment]
how am i to install the app..as there is no documentation .. and can u assign me the issue

**Comment by Jam-Burger** [comment]
> how am i to install the app..as there is no documentation .. and can u assign me the issue

If you have access to Android Studio you can build the app with gradle.
And are you a participant of SLoP 3.0?

**Comment by pratikringe46** [comment]
Assign me this issue

**Comment by pratikringe46** [comment]
Can you please assign me this issue ?

**Comment by Jam-Burger** [comment]
> Can you please assign me this issue ?

Yeah you can start working on it
